on: push
name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Publish
      uses: netlify/actions/cli@main
      with:
        args: deploy --dir=site --functions=functions
      # env:
      #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}