name: Publish on Netlify

on:
  push:
    branches:
      - main
      - feature/global_style

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish
        uses: nwtgck/actions-netlify@v2.0  # Use a specific version or tag
        with:
          publish-dir: ./dist
       # env:
        # NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Replace with your Netlify auth token
